%% Init
close all;
clear all;
fig = figure('Name','Procesory Sygna³owe');
Tab = zeros(1,3);
freq = 0;
amp = 0;
phase = 0;
freqMax = 1e4;
ampMax = 20;
%% Layout
%% Menu
set(fig, 'MenuBar','None');
% set(fig, 'Position', get(0, 'Screensize'));
menu1 = uimenu('Label','GUI');
autoScale = uimenu(menu1,'Label','Auto Scale','CallBack',...
    ['axis(axPh,[0 max(Tab(:,1)) 0 360]);'...
     'axis(axAm,[0 max(Tab(:,1)) 0 ampMax]);']);
manuLog = uimenu(menu1,'Label','Log Scale','CallBack',...
    ['axPh.XScale = ''log'';' 'axis(axPh,[1e-2 freqMax 0 ampMax]);'...
     'axis(axAm,[1e-2 freqMax 0 ampMax]);' 'axAm.XScale = ''log'';']);
manuRes = uimenu(menu1,'Label','Reset','CallBack','Tab = zeros(1,3);');
wyjscie = uimenu(menu1,'Label','Exit');
set(wyjscie,'CallBack',['instrreset;' 'close;']);
%% Manual Input
freqTxt = uicontrol(gcf,'Style','text','Units','normalized',...
    'position',[0.05 0.93 0.1 0.05],'String','Frequency');
freqIn = uicontrol(gcf,'Style','edit','Units','normalized',...
    'position',[0.05 0.9 0.1 0.05],'String','0',...
    'CallBack',['h = get(gco, ''String'');' 'freq = str2num(h);']);
ampTxt = uicontrol(gcf,'Style','text','Units','normalized',...
    'position',[0.2 0.93 0.1 0.05],'String','Amplitude');
ampIn = uicontrol(gcf,'Style','edit','Units','normalized',...
    'position',[0.2 0.9 0.1 0.05],'String','0',...
    'CallBack',['h = get(gco, ''String'');' 'amp = str2num(h);']);
phaseTxt = uicontrol(gcf,'Style','text','Units','normalized','position',...
    [0.35 0.93 0.1 0.05],'String','Phase');
phaseIn = uicontrol(gcf,'Style','edit','Units','normalized','position',...
    [0.35 0.9 0.1 0.05],'String','0','CallBack',...
    ['h = get(gco, ''String'');' 'phase = str2num(h);']);
adButton = uicontrol(gcf, 'Style','push','String','Add','Units','normalized'...
    ,'position',[0.55 0.93 0.2 0.05],'CallBack',...
    ['Tab = addSample(freqIn,ampIn,phaseIn,Tab);'...
    'drawFig(axAm, axPh, axTime, Tab,freqMax,ampMax);']);
%% Figure Amplitude
axAm = axes('Units','normalized','position',[0.05 0.58 0.93 0.23]);
axis([0 freqMax 0 ampMax]);
grid on;
ylabel('Amplitude');
drawButton = uicontrol(gcf, 'Style','push','String','Draw','Units',...
    'normalized','position',[0.75 0.93 0.2 0.05],...
    'CallBack',['drawFig(axAm, axPh, axTime, Tab,freqMax,ampMax)']);
putButton = uicontrol(gcf, 'Style','push','String','Put','Units','normalized',...
    'position',[0.55 0.88 0.2 0.05],'CallBack',...
    ['Tab = putIn(Tab);' 'drawFig(axAm, axPh, axTime, Tab,freqMax,ampMax);']);
%% Figure Phase
axPh = axes('Units','normalized','position',[0.05 0.32 0.93 0.23]);
axis([0 freqMax 0 360]);
grid on;
ylabel('Phase [°]');
xlabel('Frequency [Hz]');
%% RS 232 interface
rs = serial('COM3','BaudRate',115200);
sendButton = uicontrol(gcf, 'Style','push','String','Send to device',...
    'Units','normalized',...
    'position',[0.75 0.88 0.2 0.05],'CallBack',['sendTab2rs(rs,Tab);']);
%% Time domain signal
plotButton = uicontrol(gcf, 'Style','push','String',...
    'Plot time domain signal','Units','normalized',...
    'position',[0.55 0.83 0.4 0.05],'CallBack',['plotTimeSig(Tab);']);
axTime = axes('Units','normalized','position',[0.05 0.05 0.93 0.22]);
% title(axTime,'Time Domain Signal');
xlabel(axTime,'Time [s]')
ylabel(axTime,'value');
grid(axTime,'on');